/*

 LEVELSPRITES.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 1

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
const unsigned char levelsprites[] =
{
  0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
  0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
  0x7E,0x7E,0xDF,0xE3,0xB7,0xC9,0xAB,0xD5,
  0x97,0xE9,0xAB,0xD5,0xC7,0xFB,0x7E,0x7E
};

/* End of LEVELSPRITES.C */
