/*

 MAN.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
const unsigned char man[] =
{
  0x38,0x38,0x38,0x38,0x10,0x10,0x7C,0x7C,
  0x10,0x10,0x38,0x38,0x28,0x28,0x28,0x28
};

/* End of MAN.C */
