/* 
 Generated By GameBoyPngConverter

 Tiles map

 TileMap Size      : 32 x 18
*/ 
#define parallax_background_mapWidth 32
#define parallax_background_mapHeight 18

extern unsigned char parallax_background_map[];