/*

 BACKGROUNDMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\git\GamingMonstersGameBoySampleCode\20_sprite_tricks\backgrounddata.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define BackgroundMapWidth 20
#define BackgroundMapHeight 18
#define BackgroundMapBank 0

extern unsigned char BackgroundMap[];

/* End of BACKGROUNDMAP.H */
