/*

 KEYBOARDMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : keyboard.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define keyboardmapWidth 20
#define keyboardmapHeight 18
#define keyboardmapBank 0

extern unsigned char keyboardmap[];

/* End of KEYBOARDMAP.H */
