/*

 WELCOMEMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\git\GamingMonstersGameBoySampleCode\14_save_name\keyboard.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define welcomemapWidth 20
#define welcomemapHeight 18
#define welcomemapBank 0

extern unsigned char welcomemap[];

/* End of WELCOMEMAP.H */
