/*

 BACKGROUNDDATA.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 5

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define BackgroundDataBank 0

/* Gameboy Color palette 0 */
#define BackgroundDataCGBPal0c0 32767
#define BackgroundDataCGBPal0c1 8935
#define BackgroundDataCGBPal0c2 6596
#define BackgroundDataCGBPal0c3 5344

/* Gameboy Color palette 1 */
#define BackgroundDataCGBPal1c0 32767
#define BackgroundDataCGBPal1c1 31702
#define BackgroundDataCGBPal1c2 30528
#define BackgroundDataCGBPal1c3 26634

/* Gameboy Color palette 2 */
#define BackgroundDataCGBPal2c0 31710
#define BackgroundDataCGBPal2c1 26425
#define BackgroundDataCGBPal2c2 29596
#define BackgroundDataCGBPal2c3 21140

/* Gameboy Color palette 3 */
#define BackgroundDataCGBPal3c0 32767
#define BackgroundDataCGBPal3c1 403
#define BackgroundDataCGBPal3c2 343
#define BackgroundDataCGBPal3c3 1166

/* Gameboy Color palette 4 */
#define BackgroundDataCGBPal4c0 6076
#define BackgroundDataCGBPal4c1 8935
#define BackgroundDataCGBPal4c2 6596
#define BackgroundDataCGBPal4c3 5344

/* CGBpalette entries. */
extern unsigned char BackgroundDataCGB[];
/* Start of tile array. */
extern unsigned char BackgroundData[];

/* End of BACKGROUNDDATA.H */
