/*

 BACKGROUNDMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\git\GamingMonstersGameBoySampleCode\17_gameboy_color_backgrounds\backgrounddata.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define BackgroundMapWidth 20
#define BackgroundMapHeight 18
#define BackgroundMapBank 0

#define BackgroundMap BackgroundMapPLN0
extern unsigned char BackgroundMapPLN0[];
extern unsigned char BackgroundMapPLN1[];

/* End of BACKGROUNDMAP.H */
